// Generated by eslint-plugin-ai-code-snifftest init
import js from '@eslint/js';
import globals from 'globals';
import aiSnifftest from 'eslint-plugin-ai-code-snifftest';

export default [
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node
      }
    },
    plugins: { 'ai-code-snifftest': aiSnifftest },
    rules: {
      // Baseline
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'prefer-const': 'warn',
      'no-var': 'error',
      // Consistency
      'quotes': ['warn', 'single', { avoidEscape: true }],
      'semi': ['warn', 'always'],
      'eqeqeq': ['error', 'always'],
      // Naming (basic)
      'camelcase': ['error', { properties: 'always' }],
      // Domain-specific
      'ai-code-snifftest/no-redundant-calculations': 'warn',
      'ai-code-snifftest/no-equivalent-branches': 'warn',
      'ai-code-snifftest/prefer-simpler-logic': 'warn',
      'ai-code-snifftest/no-redundant-conditionals': 'warn',
      'ai-code-snifftest/no-unnecessary-abstraction': 'warn',
      'ai-code-snifftest/no-generic-names': 'warn',
      'ai-code-snifftest/enforce-domain-terms': 'warn',
      // Architecture guardrails
      'max-lines': ["warn",{"max":250,"skipBlankLines":true,"skipComments":true}],
      'max-lines-per-function': ["warn",{"max":50,"skipBlankLines":true,"skipComments":true}],
      'max-depth': ["warn",4],
      'complexity': ["warn",10],
      'max-params': ["warn",4],
      'max-statements': ["warn",30],
    }
  },
  {
    files: ["**/bin/*.js","**/bin/**/*.js"],
    rules: {
      'max-lines': ["error",{"max":100,"skipBlankLines":true,"skipComments":true}]
    }
  },
  {
    files: ["**/commands/**/*.js","**/lib/commands/**/*.js"],
    rules: {
      'max-lines': ["warn",{"max":150,"skipBlankLines":true,"skipComments":true}]
    }
  },
  {
    files: ["**/utils/**/*.js","**/lib/utils/**/*.js"],
    rules: {
      'max-lines': ["warn",{"max":200,"skipBlankLines":true,"skipComments":true}]
    }
  },
  {
    files: ["**/generators/**/*.js","**/lib/generators/**/*.js"],
    rules: {
      'max-lines': ["warn",{"max":250,"skipBlankLines":true,"skipComments":true}]
    }
  },
  {
    files: ["**/components/**/*.js","**/components/**/*.jsx","**/components/**/*.tsx"],
    rules: {
      'max-lines': ["warn",{"max":300,"skipBlankLines":true,"skipComments":true}]
    }
  },
  {
    files: ["**/*.test.js","**/*.spec.js","**/tests/**/*.js"],
    rules: {
      'max-lines-per-function': "off",
      'max-statements': "off",
      'complexity': "off",
      'max-depth': "off",
      'camelcase': "off"
    }
  }
];
