'use strict';

const fs = require('fs');
const path = require('path');

function writeEslintConfig(cwd, cfg) {
  const file = path.join(cwd, 'eslint.config.mjs');
  if (fs.existsSync(file) && !process.env.FORCE_ESLINT_CONFIG) {
    console.log(`Found existing ${file} — set FORCE_ESLINT_CONFIG=1 to overwrite.`);
    return;
  }
  
  // Check if architecture guardrails are enabled
  let archRulesConfig = '';
  let archOverridesConfig = '';
  const hasArchGuardrails = !!(cfg && cfg.architecture);
  if (hasArchGuardrails) {
    try {
      const { generateArchitectureRules } = require(path.join(__dirname, 'eslint-arch-config'));
      const { rules, overrides } = generateArchitectureRules(cfg.architecture);
      
      // Convert rules to ESLint config format
      const rulesStr = Object.entries(rules).map(([rule, config]) => {
        return `      '${rule}': ${JSON.stringify(config)},`;
      }).join('\n');
      
      archRulesConfig = `\n      // Architecture guardrails\n${rulesStr}`;
      
      // Convert overrides to ESLint config format
      if (overrides && overrides.length > 0) {
        const overridesStr = overrides.map(override => {
          const filesStr = JSON.stringify(override.files);
          const rulesEntries = Object.entries(override.rules).map(([rule, config]) => {
            return `      '${rule}': ${JSON.stringify(config)}`;
          }).join(',\n');
          return `  {\n    files: ${filesStr},\n    rules: {\n${rulesEntries}\n    }\n  }`;
        }).join(',\n');
        archOverridesConfig = `,\n${overridesStr}`;
      }
    } catch (err) {
      console.warn('Warning: Failed to generate architecture rules:', err.message);
    }
  }
  
  // When architecture guardrails are enabled, skip overlapping AI-friendly rules
  const aiFriendlyRules = hasArchGuardrails
    ? ''
    : '      // AI-friendly\n      \'complexity\': [\'warn\', 15],\n      \'max-depth\': [\'warn\', 4],\n      \'max-lines-per-function\': [\'warn\', 100],\n';
  
  const content = `// Generated by eslint-plugin-ai-code-snifftest init\nimport js from '@eslint/js';\nimport globals from 'globals';\nimport aiSnifftest from 'eslint-plugin-ai-code-snifftest';\n\nexport default [\n  js.configs.recommended,\n  {\n    files: ['**/*.js'],\n    languageOptions: {\n      globals: {\n        ...globals.node\n      }\n    },\n    plugins: { 'ai-code-snifftest': aiSnifftest },\n    rules: {\n      // Baseline\n      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],\n      'no-undef': 'error',\n      'prefer-const': 'warn',\n      'no-var': 'error',\n      // Consistency\n      'quotes': ['warn', 'single', { avoidEscape: true }],\n      'semi': ['warn', 'always'],\n      'eqeqeq': ['error', 'always'],\n${aiFriendlyRules}      // Naming (basic)\n      'camelcase': ['error', { properties: 'always' }],\n      // Domain-specific\n      'ai-code-snifftest/no-redundant-calculations': 'warn',\n      'ai-code-snifftest/no-equivalent-branches': 'warn',\n      'ai-code-snifftest/prefer-simpler-logic': 'warn',\n      'ai-code-snifftest/no-redundant-conditionals': 'warn',\n      'ai-code-snifftest/no-unnecessary-abstraction': 'warn',\n      'ai-code-snifftest/no-generic-names': 'warn',\n      'ai-code-snifftest/enforce-domain-terms': 'warn',${archRulesConfig}\n    }\n  }${archOverridesConfig}\n];\n`;
  // Warn-only output: convert all built-in "error" severities to "warn" in generated config
  const out = content
    .replace(/'no-undef': 'error'/g, "'no-undef': 'warn'")
    .replace(/'no-var': 'error'/g, "'no-var': 'warn'")
    .replace(/'eqeqeq': \['error', 'always'\]/g, "'eqeqeq': ['warn', 'always']")
    .replace(/'camelcase': \['error', \{ properties: 'always' \}\]/g, "'camelcase': ['warn', { properties: 'always' }]");

  fs.writeFileSync(file, out);
  console.log(`Wrote ${file}`);
}

module.exports = { writeEslintConfig };
